### ISSUE TITLE
Help how to run streamDM 

### ISSUE THREAD

**Issue by sara12345789** [huawei-noah/streamDM#61]
I need help how to run this project in eclipsce 
or it should run from cmd 

thx in advance

**Comment by nhnminh** [comment]
Hello, you could follow the steps provided here : http://huawei-noah.github.io/streamDM/docs/GettingStarted.html

By the way, before being able to work with the "Compiling the code", you should make sure that you have SCALA and SPARK on your computer. 

If you don't, please follow the tutorial here to install those two: https://www.tutorialspoint.com/apache_spark/apache_spark_installation.htm

Then, to run the first script (spark.sh), you should need some configurations: 
1. Modify $SPARK_HOME: 
+ Open ~./bash_profile (on MacOS) or ~./bashrc by some text editor
+ Add this line into that file: export SPARK_HOME="/usr/local/spark"
2. Run the script. 

That's how you could make the code runnable.
