### ISSUE TITLE
how to make it works?

### ISSUE THREAD

**Issue by fine1x** [huawei-noah/streamDM#88]
I got different errors reported by different sbt version.  How can I make it works after download it.
Should I install scala, spark before set up this package 'sbt package'?

**Comment by hmgomes** [comment]
Hi @fine1x, 

Have you installed spark 2.2.0 already? You can get it in [here](https://spark.apache.org/releases/spark-release-2-2-0.html). 
After that you can follow the tutorial in [here](http://huawei-noah.github.io/streamDM/docs/GettingStarted.html). If you have additional questions, let me know. 

Best wishes, 
Heitor

**Comment by hmgomes** [comment]
I am closing this, get in touch again if you need assistance.
