### ISSUE TITLE
StreamDM maven库 jar包

### ISSUE THREAD

**Issue by zhangjinrui2718** [huawei-noah/streamDM#91]
是否能提供maven库或者jar包的支持？

**Comment by hmgomes** [comment]
Dear @zhangjinrui2718,
Maybe it is the automatically translation that I've used, but I believe you can find what you need in here: http://huawei-noah.github.io/streamDM/docs/GettingStarted.html

Best Regards, 
Heitor

**Comment by zhangjinrui2718** [comment]
Dear @hmgomes,
Thanks for your response.

I want to integrate StreamDM with my own App,the only way i found in document is to compiler by my self.so i wonder if there is any way to access StreamDM by maven or jar?

**Comment by zhangjinrui2718** [comment]
I download the code and compiler by myself
then use
'mvn package'
'mvn install'
to access stream-DM in another app.
